require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

# minimal personal preference vs standardrb
Layout/CaseIndentation: { Enabled: false }
Lint/AssignmentInCondition: { Enabled: false }
Lint/NonLocalExitFromIterator: { Enabled: false }
Metrics: { Enabled: false }
Security/CompoundHash: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/EmptyCaseCondition: { Enabled: false }
Style/StderrPuts: { Enabled: false }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: consistent_comma }
