# load core extensions
require_relative "core_ext/array"
require_relative "core_ext/deep_dup"
require_relative "core_ext/enumerable"
require_relative "core_ext/hash"
require_relative "core_ext/integer"
require_relative "core_ext/math"
require_relative "core_ext/numeric"
require_relative "core_ext/numpy"
require_relative "core_ext/object"
require_relative "core_ext/range"
require_relative "core_ext/string"
